---
- name: "Validate server log file (when enabled)"
  when:
    - server_log_validation is defined
    - server_log_validation | bool
  block:
    - name: "Ensure required parameter(s) are provided."
      ansible.builtin.assert:
        that:
          - server_log_dir is defined
          - server_log_validation_min_size is defined
        quiet: true
        fail_msg: "{{ server_log_dir | default('server_log_dir') }} is invalid"

    - name: "Stat server log file"
      ansible.builtin.stat:
        path: "{{ server_log_dir }}"
      register: server_log_stat

    - name: "Assert server log file exists"
      ansible.builtin.assert:
        that:
          - server_log_stat.stat.exists
        quiet: true
        fail_msg: "{{ server_log_dir }} is invalid"

    - name: "Set error handling behavior"
      ansible.builtin.set_fact:
        server_log_fail_if_error_is_found: true
      when:
        - server_log_fail_if_error_is_found is not defined

    - name: "Read the content of server log"
      ansible.builtin.slurp:
        src: "{{ server_log_dir }}"
      register: server_log_slurped

    - name: "Set number of characters in log"
      ansible.builtin.set_fact:
        server_log_content: "{{ server_log_slurped['content'] | b64decode }}"
        nb_chars_in_server_log: "{{ server_log_slurped['content'] | b64decode | length }}"

    - name: "Check that log is not empty"
      ansible.builtin.assert:
        that:
          - nb_chars_in_server_log is defined
          - nb_chars_in_server_log | int > server_log_validation_min_size
        quiet: true

    - name: "Set expected string for fail error message"
      ansible.builtin.set_fact:
        error_label: 'ERROR'
      when:
        - error_label is not defined

    - name: "Check logfile does not contain error lines"
      when:
        - server_log_fail_if_error_is_found | bool
      block:
        - name: "Display logfile if error label is found"
          ansible.builtin.debug:
            msg: "{{ server_log_content }}"
          when:
            - error_label in server_log_content

        - name: "Assert logfile does not contain error label"
          ansible.builtin.assert:
            that:
              - error_label not in server_log_content
            quiet: true
            fail_msg: "Server logfile contains {{ error_label }} error lines."
