---
- name: "Restart {{ amq_streams_broker.service_name }}"
  ansible.builtin.service:
    name: "{{ amq_streams_broker.service_name }}"
    state: restarted
  become: "{{ amq_streams_install_requires_become | default(true) }}"
