---
- name: "Ensure required parameters are provided."
  ansible.builtin.assert:
    that:
      - user is defined
      - topic_name is defined
    quiet: true

- name: "Change ACL on {{ user }} for {{ topic_name }}."
  block:
    - name: "Use bootstrap server to create topic {{ topic_name }}"
      ansible.builtin.include_tasks: cli/bootstrap.yml
      vars:
        main_argument: "--{{ acl_switch | default('allow') }}-principal User:{{ user }} --operation Write --topic {{ topic_name }}"
        bootstrap_operator: "--add"
        script: "{{ amq_streams_broker_kafka_acl_script }}"
