---
- name: "Ensure required parameter(s) are defined."
  ansible.builtin.assert:
    that:
      - amq_stream_cruise_control_home is defined
    quiet: true

- name: "Ensure requirements for Cruise Control are met."
  ansible.builtin.include_role:
    name: amq_streams_common
    tasks_from: main.yml

- name: "Ensure Cruise Control artifacts are available."
  ansible.builtin.include_role:
    name: amq_streams_common
    tasks_from: rhn/main.yml
  vars:
    rhn_product_archive_file_pattern: "{{ amq_streams_cruise_control_rhn_product_archive_file_pattern }}"

- name: "Ensure Cruise Control artifacts is properly installed."
  ansible.builtin.include_role:
    name: amq_streams_common
    tasks_from: install.yml
  vars:
    amq_streams_common_archive_file: "{{ amq_streams_cruise_control_archive_file }}"
    amq_streams_common_archive_creates_control_file: "{{ amq_streams_cruise_control_home }}/config"
    rhn_product_archive_file_pattern: "{{ amq_streams_cruise_control_rhn_product_archive_file_pattern }}"

- name: "Deploy custom log4j config (if provided)"
  become: "{{ amq_streams_cruise_control_logfiles_requires_priv_escalation }}"
  when:
    - amq_streams_cruise_control_logfilename is defined
  block:
    - name: "Ensure dirname for logfile exits {{ amq_streams_cruise_control_logfilename | dirname }}"
      ansible.builtin.file:
        path: "{{ amq_streams_cruise_control_logfilename | dirname }}"
        state: directory

    - name: "Ensure log4j logging is properly configured"
      ansible.builtin.template:
        src: "{{ amq_streams_cruise_control_log4j_template }}"
        dest: "{{ amq_streams_cruise_control_path_to_log4j_properties }}"
        owner: "{{ amq_streams_cruise_control_user | default(omit) }}"
        group: "{{ amq_streams_cruise_control_group | default(omit) }}"
        mode: 0644

- name: "Ensure capacity.json is properly configured"
  ansible.builtin.include_tasks: capacity.yml
  when:
    - amq_streams_broker_inventory_group is defined and amq_streams_broker_inventory_group | length > 0

- name: "Ensure JAAS config is deployed and up to date (if enabled)"
  ansible.builtin.include_tasks: jaas_config.yml
  when:
    - amq_streams_broker_inter_broker_auth_sasl_protocol is defined and amq_streams_broker_inter_broker_auth_sasl_mechanisms is defined and amq_streams_cruise_control_zk_sasl_jaas_config is defined

- name: "Ensure Cruise Control service is running (if enable)."
  ansible.builtin.include_tasks: service.yml
