---
- name: "Configure firewalld for Cruise Control (if enable)."
  ansible.builtin.include_role:
    name: amq_streams_common
    tasks_from: firewalld.yml
  vars:
    service_port: "{{ amq_streams_cruise_control_port }}"
  when:
    - amq_streams_firewalld_enabled is defined and amq_streams_firewalld_enabled
    - amq_streams_cruise_control_port is defined

- name: "Deploy Cruise Control as a systemd service."
  ansible.builtin.include_role:
    name: amq_streams_common
    tasks_from: systemd.yml
  vars:
    server_name: "{{ amq_streams_cruise_control_service_name }}"
    server_start: "{{ amq_streams_cruise_control_server_start }}"
    server_stop: "{{ amq_streams_cruise_control_server_stop }}"
    server_config: "{{ amq_streams_cruise_control_server_config }}"
    server_config_template: "{{ amq_streams_cruise_control_config_properties_template }}"
    server_user: "{{ amq_streams_cruise_control_user }}"
    server_group: "{{ amq_streams_cruise_control_group }}"
    server_java_opts: "{{ amq_streams_cruise_control_java_opts | default('') }}"
