---
redhat_streams_exporter_enabled: True
redhat_streams_exporter_target_arch: "{{ ansible_architecture }}"
redhat_streams_exporter_version: 1.7.0
redhat_streams_exporter_download_base_url: 'https://github.com/danielqsj/kafka_exporter/releases/download/'
redhat_streams_exporter_download_url: "{{ redhat_streams_exporter_download_base_url }}v{{ redhat_streams_exporter_version }}/kafka_exporter-{{ redhat_streams_exporter_version }}.{{ redhat_streams_exporter_target_system }}-{{ redhat_streams_exporter_target_arch }}.tar.gz"
redhat_streams_exporter_archive_folder: "kafka_exporter-{{ redhat_streams_exporter_version }}.{{ redhat_streams_exporter_target_system }}-{{ redhat_streams_exporter_target_arch }}"
redhat_streams_exporter_archive_name: "{{ redhat_streams_exporter_archive_folder }}.tar.gz"
redhat_streams_exporter_download_dir: "{{ lookup('env','PWD') | default('/opt') }}"
redhat_streams_exporter_download_path: "{{ redhat_streams_exporter_download_dir }}/{{ redhat_streams_exporter_archive_name }}"
redhat_streams_exporter_download_host: localhost
redhat_streams_exporter_home: "{{ redhat_streams_common_home }}"
redhat_streams_exporter_server_start: "{{ redhat_streams_common_home }}/{{ redhat_streams_exporter_archive_folder }}/{{ redhat_streams_exporter_server_start_script }}"
redhat_streams_exporter_dependencies:
  - tar
  - unzip
redhat_streams_exporter_service_name: redhat_streams_exporter
redhat_streams_exporter_server_port: 9308
redhat_streams_exporter_server_start_script: kafka_exporter

# redhat_streams_exporter_server_config: /etc/redhat_streams_exporter
# redhat_streams_exporter_config_template: templates/exporter.properties.j2
redhat_streams_exporter_systemd_env_file: /etc/redhat_streams_exporter.conf
redhat_streams_exporter_service_config_template: templates/service.conf.j2
# redhat_streams_exporter_service_config_template: templates/service.conf.j2
redhat_streams_exporter_user: redhat_streams_exporter
redhat_streams_exporter_group: redhat_streams
redhat_streams_exporter_java_opts: ''
redhat_streams_exporter_server_port_delay: 0
redhat_streams_exporter_server_port_skip_wait: False
redhat_streams_exporter_broker_server_host: "{{ groups['brokers'][0] | default('localhost') }}"
redhat_streams_exporter_broker_server_port: 9092
redhat_streams_exporter_server_extra_args: "--group.filter='.*' --topic.filter='.*' --offset.show-all --verbosity=0 --kafka.version='{{ redhat_streams_common_product_version }}'  --kafka.server={{ redhat_streams_exporter_broker_server_host }}:{{ redhat_streams_exporter_broker_server_port }}"
