---
- name: "Ansible playbook to install a Kafka Connect cluster"
  hosts: all
  tasks:
    - name: "Ensure Kafka Connect is running and available."
      ansible.builtin.include_role:
        name: amq_streams_connect
      vars:
        connectors:
          - { name: "file", path: "connectors/file.yml" }
