---
amq_streams_install_dir: "/opt"
amq_streams_kafka_home: "{{ amq_streams_install_dir }}/kafka_{{ amq_streams_common_version }}/"
amq_streams_kraft_config_dir: "{{ amq_streams_kafka_home }}/config"
amq_streams_kraft_data_dir: "{{ amq_streams_kafka_home }}/data/kraft"
amq_streams_cluster_id: ""
amq_streams_kraft_node_id: 1
amq_streams_kraft_listener_port: 9092
amq_streams_kraft_controller_port: 9093
amq_streams_kraft_controller_quorum_voters: "1@{{ ansible_host }}:{{ amq_streams_kraft_controller_port }}"
amq_streams_kraft_listeners:
  - "PLAINTEXT://0.0.0.0:{{ amq_streams_kraft_listener_port }}"
  - "CONTROLLER://0.0.0.0:{{ amq_streams_kraft_controller_port }}"
amq_streams_kraft_advertised_listeners:
  - "PLAINTEXT://{{ ansible_host }}:{{ amq_streams_kraft_listener_port }}"
amq_streams_kraft_controller_listener_names: "CONTROLLER"
amq_streams_kraft_inter_broker_listener_name: "PLAINTEXT"
amq_streams_kraft_process_roles: "broker,controller"
amq_streams_kraft_log_dirs: "{{ amq_streams_kraft_data_dir }}"
amq_streams_kraft_log_retention_hours: 168
amq_streams_kraft_priv_escalation: yes
