---
- name: "Ensure prerequirements for collection are met."
  ansible.builtin.include_role:
    name: amq_streams_common

- name: "Ensure prerequirements for collection are met."
  ansible.builtin.include_role:
    name: amq_streams_common
    tasks_from: user_group.yml
  vars:
    user: "{{ amq_streams_install_broker_user }}"
    group: "{{ amq_streams_install_broker_group }}"
  when:
    - amq_streams_install_broker_user is defined
    - amq_streams_install_broker_group is defined

- name: "Download artefacts from project's website"
  ansible.builtin.include_role:
    name: amq_streams_common
    tasks_from: download.yml

- name: "Configure firewalld  for Broker (if enable)."
  ansible.builtin.include_role:
    name: amq_streams_common
    tasks_from: firewalld.yml
  vars:
    service_port: "{{ amq_streams_install_bootstrap_server_port }}"
  when:
    - amq_streams_firewalld_enabled is defined and amq_streams_firewalld_enabled
    - amq_streams_install_bootstrap_server_port is defined

- name: "Configure firewalld for Zookeeper (if enable)."
  ansible.builtin.include_role:
    name: amq_streams_common
    tasks_from: firewalld.yml
  vars:
    service_port: "{{ amq_streams_install_zookeeper_port }}"
    firewalld_state_check: false
  when:
    - amq_streams_firewalld_enabled is defined and amq_streams_firewalld_enabled
    - amq_streams_install_bootstrap_server_port is defined

- name: "Ensure Zookeeper is running."
  ansible.builtin.include_role:
    name: amq_streams_zookeeper

- name: "Ensure Broker is running."
  ansible.builtin.include_role:
    name: amq_streams_broker
