---
- name: "Set required JDK package (if Java version is provided)."
  ansible.builtin.set_fact:
    amq_streams_common_dependencies: "{{ [amq_streams_common.dependencies + ['java-{{ amq_streams_common.java.version }}-openjdk-headless']] | flatten }}"
  when:
    - amq_streams_common.java is defined
    - amq_streams_common.java.version is defined

- name: "Ensure all required system dependencies are present."
  ansible.builtin.package:
    name: "{{ amq_streams_common_dependencies }}"
    state: present
  when:
    - not amq_streams_common_skip_deps is defined
    - amq_streams_common.dependencies is defined
    - amq_streams_common.dependencies | length > 0
