---
- name: "Ensure required parameter(s) are provided."
  ansible.builtin.assert:
    that:
      - user is defined and user | length > 0
      - group is defined and group | length > 0
    quiet: true

- name: "Ensure required group {{ group }} exists."
  become: "{{ amq_streams_common_escalade_privilege_group_create }}"
  ansible.builtin.group:
    name: "{{ group }}"

- name: "Ensure required user {{ user }} exists."
  become: "{{ amq_streams_common_escalade_privilege_user_create }}"
  ansible.builtin.user:
    name: "{{ user }}"
    group: "{{ group }}"
