---
- name: Verify
  hosts: all
  tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Check if amq_streams service started
      ansible.builtin.assert:
        that:
          - ansible_facts.services["amq_streams_broker.service"]["state"] == "running"
          - ansible_facts.services["amq_streams_broker.service"]["status"] == "enabled"
          - ansible_facts.services["amq_streams_zookeeper.service"]["state"] == "running"
          - ansible_facts.services["amq_streams_zookeeper.service"]["status"] == "enabled"
