argument_specs:
    main:
        options:
            # line 2 of defaults/main.yml
            amq_streams_broker_create_topic_script:
                default: "{{ amq_streams_common_home }}/bin/kafka-topics.sh"
                description: "TODO document argument"
                type: "str"

            # line 3 of defaults/main.yml
            amq_streams_broker_enabled:
                default: true
                description: "TODO document argument"
                type: "bool"

            # line 4 of defaults/main.yml
            amq_streams_broker_server_start:
                default: "{{ amq_streams_common_home }}/bin/kafka-server-start.sh"
                description: "TODO document argument"
                type: "str"

            # line 5 of defaults/main.yml
            amq_streams_broker_config:
                default: "/etc/amq_streams_broker.properties"
                description: "TODO document argument"
                type: "str"

            # line 6 of defaults/main.yml
            amq_streams_broker_service_name:
                default: "amq_streams_broker"
                description: "TODO document argument"
                type: "str"

            # line 7 of defaults/main.yml
            amq_streams_broker_user:
                default: "amq_streams_broker"
                description: "TODO document argument"
                type: "str"

            # line 8 of defaults/main.yml
            amq_streams_broker_listener_port:
                default: 9092
                description: "TODO document argument"
                type: "int"

            # line 9 of defaults/main.yml
            amq_streams_broker_listener_internal_port:
                default: 9091
                description: "TODO document argument"
                type: "int"

            # line 10 of defaults/main.yml
            amq_streams_broker_group:
                default: "amq_streams"
                description: "TODO document argument"
                type: "str"

            # line 11 of defaults/main.yml
            amq_streams_broker_service_config_template:
                default: "templates/service.conf.j2"
                description: "TODO document argument"
                type: "str"

            # line 12 of defaults/main.yml
            amq_streams_broker_service_config_file:
                default: "/etc/broker.conf"
                description: "TODO document argument"
                type: "str"

            # line 13 of defaults/main.yml
            amq_streams_broker_data_dir:
                default: "/var/lib/{{ amq_streams_broker_service_name }}"
                description: "TODO document argument"
                type: "str"

            # line 14 of defaults/main.yml
            amq_streams_broker_logs_dir:
                default: "/var/log/{{ amq_streams_broker_service_name }}/"
                description: "TODO document argument"
                type: "str"

            # line 15 of defaults/main.yml
            amq_streams_broker_num_network_threads:
                default: 3
                description: "TODO document argument"
                type: "int"

            # line 16 of defaults/main.yml
            amq_streams_broker_num_io_threads:
                default: 8
                description: "TODO document argument"
                type: "int"

            # line 17 of defaults/main.yml
            amq_streams_broker_buffer_send_bytes:
                default: 102400
                description: "TODO document argument"
                type: "int"

            # line 18 of defaults/main.yml
            amq_streams_broker_buffer_bytes:
                default: 102400
                description: "TODO document argument"
                type: "int"

            # line 19 of defaults/main.yml
            amq_streams_broker_socket_request_max_bytes:
                default: 104857600
                description: "TODO document argument"
                type: "int"

            # line 20 of defaults/main.yml
            amq_streams_broker_num_partitions:
                default: 1
                description: "TODO document argument"
                type: "int"

            # line 21 of defaults/main.yml
            amq_streams_broker_num_recovery_threads_per_data_dir:
                default: 1
                description: "TODO document argument"
                type: "int"

            # line 22 of defaults/main.yml
            amq_streams_broker_offsets_topic_replication_factor:
                default: 1
                description: "TODO document argument"
                type: "int"

            # line 23 of defaults/main.yml
            amq_streams_broker_transaction_state_log_replication_factor:
                default: 1
                description: "TODO document argument"
                type: "int"

            # line 24 of defaults/main.yml
            amq_streams_broker_transaction_state_log_min_isr:
                default: 1
                description: "TODO document argument"
                type: "int"

            # line 25 of defaults/main.yml
            amq_streams_broker_log_retention_hours:
                default: 168
                description: "TODO document argument"
                type: "int"

            # line 26 of defaults/main.yml
            amq_streams_broker_log_retention_check_interval_ms:
                default: 300000
                description: "TODO document argument"
                type: "int"

            # line 27 of defaults/main.yml
            amq_streams_broker_zookeeper_connection_timeout_ms:
                default: 30000
                description: "TODO document argument"
                type: "int"

            # line 28 of defaults/main.yml
            amq_streams_broker_zookeeper_session_timeout_ms:
                default: 18000
                description: "TODO document argument"
                type: "int"

            # line 29 of defaults/main.yml
            amq_streams_broker_group_initial_rebalance_delay_ms:
                default: 0
                description: "TODO document argument"
                type: "int"

            # line 30 of defaults/main.yml
            amq_streams_broker_properties_template:
                default: "templates/server.properties.j2"
                description: "TODO document argument"
                type: "str"

            # line 31 of defaults/main.yml
            amq_streams_broker_java_heap_opts:
                default: "-Xmx1G -Xms1G"
                description: "TODO document argument"
                type: "str"

            # line 33 of defaults/main.yml
            amq_streams_broker_bootstrap_server_host:
                default: "localhost"
                description: "TODO document argument"
                type: "str"

            # line 34 of defaults/main.yml
            amq_streams_broker_bootstrap_server_port:
                default: 9092
                description: "TODO document argument"
                type: "int"

            # line 36 of defaults/main.yml
            amq_streams_firewalld_package_name:
                default: "['firewalld']"
                description: "TODO document argument"
                type: "list"

            # line 38 of defaults/main.yml
            amq_streams_firewalld_enabled:
                default: false
                description: "TODO document argument"
                type: "bool"

            # line 40 of defaults/main.yml
            amq_streams_broker_instance_count_enabled:
                default: true
                description: "TODO document argument"
                type: "bool"

            # line 41 of defaults/main.yml
            amq_streams_broker_instance_count:
                default: 0
                description: "TODO document argument"
                type: "int"

            # line 43 of defaults/main.yml
            amq_streams_deployment_balance_check_enabled:
                default: true
                description: "TODO document argument"
                type: "bool"

            # line 45 of defaults/main.yml
            amq_streams_broker_zookeeper_host_default_value:
                default: "localhost"
                description: "TODO document argument"
                type: "str"

            # line 46 of defaults/main.yml
            amq_streams_broker_zookeeper_port_default_value:
                default: 2181
                description: "TODO document argument"
                type: "int"

            # line 47 of defaults/main.yml
            amq_streams_broker_zookeeper_wait:
                default: true
                description: "TODO document argument"
                type: "bool"

            # line 50 of defaults/main.yml
            amq_streams_zookeeper_auth_enabled:
                default: "false"
                description: "TODO document argument"
                type: "str"

            # line 51 of defaults/main.yml
            amq_streams_broker_zookeeper_auth_config:
                default: "/etc/broker-jaas.conf"
                description: "TODO document argument"
                type: "str"

            # line 52 of defaults/main.yml
            amq_streams_broker_zookeeper_auth_config_template:
                default: "templates/broker-jaas.conf.j2"
                description: "TODO document argument"
                type: "str"

            # line 55 of defaults/main.yml
            amq_streams_broker_listeners:
                default: "['PLAINTEXT://:{{ amq_streams_broker_listener_port }}']"
                description: "TODO document argument"
                type: "list"

            # line 61 of defaults/main.yml
            amq_streams_broker_auth_enabled:
                default: "false"
                description: "TODO document argument"
                type: "str"

            # line 62 of defaults/main.yml
            amq_streams_broker_auth_scram_enabled:
                default: "false"
                description: "TODO document argument"
                type: "str"

            # line 63 of defaults/main.yml
            amq_streams_connect_broker_auth_username:
                default: "broker"
                description: "TODO document argument"
                type: "str"

            # line 64 of defaults/main.yml
            amq_streams_connect_broker_auth_password:
                default: "PLEASE_CHANGEME_IAMNOTGOOD_FOR_PRODUCTION"
                description: "TODO document argument"
                type: "str"

            # line 66 of defaults/main.yml
            amq_streams_broker_auth_listeners:
                default: "['PLAINTEXT:PLAINTEXT']"
                description: "TODO document argument"
                type: "list"

            # line 71 of defaults/main.yml
            amq_streams_broker_auth_sasl_mechanisms:
                default: "['PLAIN']"
                description: "TODO document argument"
                type: "list"

            # line 75 of defaults/main.yml
            amq_streams_broker_server_log_validation_min_size:
                default: 20
                description: "TODO document argument"
                type: "int"

            # line 77 of defaults/main.yml
            amq_streams_broker_inventory_group:
                default: "{{ groups['brokers'] | default('') }}"
                description: "TODO document argument"
                type: "str"

            # line 78 of defaults/main.yml
            amq_streams_zookeeper_inventory_group:
                default: "{{ groups['zookeepers'] | default('') }}"
                description: "TODO document argument"
                type: "str"
