---
- name: "Ensure user and group exists (if provided)."
  ansible.builtin.include_role:
    name: amq_streams_common
    tasks_from: prereqs.yml
  vars:
    prereqs_user: "{{ amq_streams_connect_user }}"
    prereqs_group: "{{ amq_streams_connect_group }}"
