---
- name: "Ansible Playbook to install a Kafka cluster (+Zookeeper)"
  hosts: all
  vars:
    amq_streams_common_download_node: ""
    amq_streams_common_download_dir: "/tmp"
    topic_name: myTopic
  roles:
    - role: amq_streams_zookeeper   
  tasks:
    - name: "Ensure AMQ Streams Broker is running and available."
      ansible.builtin.include_role:
        name: amq_streams_broker
      vars:
        amq_streams_common_skip_download: true

    - name: "Ensures topic {{ topic_name }} exist."
      ansible.builtin.include_role:
        name: amq_streams_broker
        tasks_from: topic/create.yml
      loop:
        - { name: monTopic, partition: 3 }
        - { name: topic2, partition: 2 }

    - name: "Describe created topic."
      ansible.builtin.include_role:
        name: amq_streams_broker
        tasks_from: topic/describe.yml
  post_tasks:
    - name: "Display numbers of Zookeeper instances managed by Ansible."
      ansible.builtin.debug:
        msg: "Numbers of Zookeeper instances: {{ amq_streams_zookeeper_instance_count }}."
      when:
        - amq_streams_zookeeper_instance_count_enabled is defined and amq_streams_zookeeper_instance_count_enabled

    - name: "Display numbers of broker instances managed by Ansible."
      ansible.builtin.debug:
        msg: "Numbers of broker instances: {{ amq_streams_broker_instance_count }}."
      when:
        - amq_streams_broker_instance_count_enabled is defined and amq_streams_broker_instance_count_enabled

    - name: "Validate that deployment is functional."
      ansible.builtin.include_role:
        name: amq_streams_zookeeper
        tasks_from: validate.yml
