---
- name: "Ansible Playbook to install a Zookeeper ensemble"
  hosts: zookeepers
  vars:
    amq_streams_common_download_dir: "/tmp"
    amq_streams_zookeeper_auth_user: amq_streams_user
    amq_streams_zookeeper_auth_pass: amq_streams_pass
  roles:
    - role: amq_streams_zookeeper
  tasks:
    - name: "Ensure Zookeeper is running and available."
      ansible.builtin.include_role:
        name: amq_streams_zookeeper
  post_tasks:
    - name: "Display numbers of Zookeeper instances managed by Ansible."
      ansible.builtin.debug:
        msg: "Numbers of Zookeeper instances: {{ amq_streams_zookeeper_instance_count }}."
      when:
        - amq_streams_zookeeper_instance_count is defined

- name: "Ansible Playbook to install a Kafka cluster"
  hosts: brokers
  vars:
    amq_streams_common_download_dir: "/tmp"
    amq_streams_zookeeper_auth_user: amq_streams_user
    amq_streams_zookeeper_auth_pass: amq_streams_pass
    topic_name: myTopic
  roles:
    - role: amq_streams_broker
  tasks:
    - name: "Ensure AMQ Streams Broker is running and available."
      ansible.builtin.include_role:
        name: amq_streams_broker
      vars:
        amq_streams_common_skip_download: true

    - name: "Ensures topic {{ topic_name }} exist."
      ansible.builtin.include_role:
        name: amq_streams_broker
        tasks_from: topic/create.yml
      loop:
        - { name: monTopic, partition: 3 }
        - { name: topic2, partition: 2 }

    - name: "Describe created topic."
      ansible.builtin.include_role:
        name: amq_streams_broker
        tasks_from: topic/describe.yml
  post_tasks:
    - name: "Display numbers of broker instances managed by Ansible."
      ansible.builtin.debug:
        msg: "Numbers of broker instances: {{ amq_streams_broker_instance_count }}."
      when:
        - amq_streams_broker_instance_count is defined
