---
- name: "Automate AMQ Streams install"
  hosts: "{{ brokers_target_group | default('brokers') }}"
  vars:
    amq_streams_brokers_validate_playbook: True
  collections:
    - middleware_automation.amq_streams
  roles:
    - role: amq_streams_broker
  post_tasks:
    - name: "Validate that Broker deployment is functional."
      ansible.builtin.include_role:
        name: amq_streams_broker
        tasks_from: validate.yml
      when:
        - amq_streams_brokers_validate_playbook is defined and amq_streams_brokers_validate_playbook
