argument_specs:
    main:
        options:
            # line 2 of defaults/main.yml
            amq_streams_exporter_enabled:
                default: true
                description: "TODO document argument"
                type: "bool"

            # line 3 of defaults/main.yml
            amq_streams_exporter_target_arch:
                default: "{{ ansible_architecture }}"
                description: "Specify physical architecture of target host"
                type: "str"

            # line 4 of defaults/main.yml
            amq_streams_exporter_version:
                default: "1.7.0"
                description: "Exporter version to be used"
                type: "str"

            # line 5 of defaults/main.yml
            amq_streams_exporter_download_base_url:
                default: "https://github.com/danielqsj/kafka_exporter/releases/download/"
                description: "Base URL for downloading Exporter archive"
                type: "str"

            # line 6 of defaults/main.yml
            amq_streams_exporter_download_url:
                default: "{{ amq_streams_exporter_download_base_url }}v{{ amq_streams_exporter_version }}/kafka_exporter-{{ amq_streams_exporter_version }}.{{ amq_streams_exporter_target_system }}-{{ amq_streams_exporter_target_arch }}.tar.gz"
                description: "Download URL for Exporter archive"
                type: "str"

            # line 7 of defaults/main.yml
            amq_streams_exporter_archive_folder:
                default: "kafka_exporter-{{ amq_streams_exporter_version }}.{{ amq_streams_exporter_target_system }}-{{ amq_streams_exporter_target_arch }}"
                description: "Folder name for Exporter"
                type: "str"

            # line 8 of defaults/main.yml
            amq_streams_exporter_archive_name:
                default: "{{ amq_streams_exporter_archive_folder }}.tar.gz"
                description: "Exporter archive name"
                type: "str"

            # line 9 of defaults/main.yml
            amq_streams_exporter_download_dir:
                default: "{{ lookup('env','PWD') | default('/opt') }}"
                description: "Download dirname"
                type: "str"

            # line 10 of defaults/main.yml
            amq_streams_exporter_download_path:
                default: "{{ amq_streams_exporter_download_dir }}/{{ amq_streams_exporter_archive_name }}"
                description: "Path to download directory (on controller)"
                type: "str"

            # line 11 of defaults/main.yml
            amq_streams_exporter_download_host:
                default: "localhost"
                description: "Hostname of download host (if not controller)"
                type: "str"

            # line 12 of defaults/main.yml
            amq_streams_exporter_home:
                default: "{{ amq_streams_common_home }}"
                description: "Exporter home directory"
                type: "str"

            # line 13 of defaults/main.yml
            amq_streams_exporter_server_start:
                default: "{{ amq_streams_common_home }}/{{ amq_streams_exporter_archive_folder }}/{{ amq_streams_exporter_server_start_script }}"
                description: "Exporter start script"
                type: "str"

            # line 14 of defaults/main.yml
            amq_streams_exporter_dependencies:
                default: "['tar', 'unzip']"
                description: "Dependencies required by Exporter (RPM packages names)"
                type: "list"

            # line 17 of defaults/main.yml
            amq_streams_exporter_service_name:
                default: "amq_streams_exporter"
                description: "Service name for the Exporter instance"
                type: "str"

            # line 18 of defaults/main.yml
            amq_streams_exporter_server_port:
                default: 9308
                description: "Exporter server port"
                type: "int"

            # line 19 of defaults/main.yml
            amq_streams_exporter_server_start_script:
                default: "kafka_exporter"
                description: "Exporter start script name"
                type: "str"

            # line 23 of defaults/main.yml
            amq_streams_exporter_systemd_env_file:
                default: "/etc/amq_streams_exporter.conf"
                description: "Exporter service config file"
                type: "str"

            # line 24 of defaults/main.yml
            amq_streams_exporter_service_config_template:
                default: "templates/service.conf.j2"
                description: "Templates to use for the systemd service for Exporter"
                type: "str"

            # line 26 of defaults/main.yml
            amq_streams_exporter_user:
                default: "amq_streams_exporter"
                description: "User account, on targets, running the Exporter"
                type: "str"

            # line 27 of defaults/main.yml
            amq_streams_exporter_group:
                default: "amq_streams"
                description: "Group account, on targets, Exporter user belongs to"
                type: "str"

            # line 28 of defaults/main.yml
            amq_streams_exporter_java_opts:
                default: ""
                description: "Java options to pass to Exporter JVM"
                type: "str"

            # line 29 of defaults/main.yml
            amq_streams_exporter_server_port_delay:
                default: 0
                description: "Delay before checking Exporter server's port availability"
                type: "int"

            # line 30 of defaults/main.yml
            amq_streams_exporter_server_port_skip_wait:
                default: false
                description: "Skip waiting for Exporter server port to be available"
                type: "bool"

            # line 31 of defaults/main.yml
            amq_streams_exporter_broker_server_host:
                default: "{{ groups['brokers'][0] | default('localhost') }}"
                description: "Broker's hostname"
                type: "str"

            # line 32 of defaults/main.yml
            amq_streams_exporter_broker_server_port:
                default: 9092
                description: "Broker's port"
                type: "int"

            # line 33 of defaults/main.yml
            amq_streams_exporter_server_extra_args:
                default: "--group.filter='.*' --topic.filter='.*' --offset.show-all --verbosity=0 --kafka.version='{{ amq_streams_common_product_version }}'  --kafka.server={{ amq_streams_exporter_broker_server_host }}:{{ amq_streams_exporter_broker_server_port }}"
                description: "Extra arguments to Exporter service start command"
                type: "str"
