---
- name: "Ensure required parameter(s) are provided."
  ansible.builtin.include_role:
    name: amq_streams_common
    tasks_from: validation/service.yml
  vars:
    service_name: "{{ amq_streams_exporter_service_name }}"
