---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 6 * * *'

jobs:
  galaxy-importer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core galaxy-importer
      - name: Build collection
        run: ansible-galaxy collection build .
      - name: Run galaxy-importer
        run: python -m galaxy_importer.main middleware_automation-amq_streams-*.tar.gz
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Run cspell
        uses: streetsidesoftware/cspell-action@v9
        with:
          incremental_files_only: false
          use_cspell_files: true

  ci:
    uses: ansible-middleware/github-actions/.github/workflows/ci.yml@rootperm
    secrets: inherit
    with:
      fqcn: 'middleware_automation/amq_streams'
      root_permission_varname: 'amq_streams_install_requires_become'
      molecule_tests: >-
        [ "default", "amq_streams_kraft" ]
