---
name: CI
on:
  push:
    branches:
      - AMW-162
  pull_request:
  schedule:
    - cron: '0 6 * * *'

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Run cspell
        uses: streetsidesoftware/cspell-action@v9
        with:
          incremental_files_only: false
          use_cspell_files: true

  ci:
    uses: ansible-middleware/github-actions/.github/workflows/ci.yml@rootperm
    secrets: inherit
    with:
      fqcn: 'middleware_automation/amq_streams'
      root_permission_varname: 'amq_streams_install_requires_become'
      molecule_tests: >-
        [ "default", "amq_streams_kraft" ]
