---
name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  COLORTERM: 'yes'
  TERM: 'xterm-256color'
  PYTEST_ADDOPTS: '--color=yes'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.11"]
        molecule_test:
          - default
          - all_auth
          - connect
          - ssl_auth_sasl
          - ssl_no_auth
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ansible_collections/middleware_automation/amq_streams

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip'

      - name: Create default collection path
        run: |
          mkdir -p /home/runner/.ansible/
          ln -s /home/runner/work/amq_streams/amq_streams /home/runner/.ansible/collections

      - name: Install yamllint, ansible and molecule
        run: |
          python -m pip install --upgrade pip
          pip install yamllint 'molecule[docker]~=3.5.2' ansible-core flake8 ansible-lint voluptuous
          pip install -r ansible_collections/middleware_automation/amq_streams/requirements.txt
          ansible-galaxy collection install -r ansible_collections/middleware_automation/amq_streams/requirements.yml -p /home/runner/.ansible/collections --force-with-deps

      - name: Install ansible-lint custom rules
        uses: actions/checkout@v2
        with:
          repository: ansible-middleware/ansible-lint-custom-rules
          path: ansible_collections/ansible-lint-custom-rules/

      - name: Run sanity tests
        run: ansible-test sanity -v --color --python ${{ matrix.python_version }} --exclude changelogs/fragments/.gitignore --skip-test symlinks --skip-test shebang
        working-directory: ./ansible_collections/middleware_automation/amq_streams

      - name: Run molecule test
        run: molecule test -s ${{ matrix.molecule_test }}
        working-directory: ./ansible_collections/middleware_automation/amq_streams
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
